#!/bin/bash

pushd ~
for repo in ankurdave.com ankur-photos bagel cloudclustering cloudclustering-paper cs61a cs61c cs61c-proj{1,2,3,4} cs70 distboggle dotfiles engl31ac kmeans-spark latex math53 music-index physics7a quorastats resume spark-pagerank-performance
do
    pushd $repo
    ssh dave-server git init --bare ~/git/$repo
    git push --mirror dave-server:git/$repo
    popd
done
popd