#!/bin/bash

pushd ~/repos
for repo in $(find . -mindepth 1 -maxdepth 1 -type d | sed 's/^\.\///')
do
    pushd $repo
    ssh dave-server "if [ ! -d ~/git/$repo ]; then git init --bare ~/git/$repo; fi"
    git push --mirror dave-server:git/$repo
    popd
done
popd
